import type { Metadata } from "next";
import { Check, Fingerprint, ShieldX } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Card } from "@/components/ui/card";
import { criticalMutationReceipt, runProofSuite } from "@/domain/control-engine";

export const metadata: Metadata = { title: "Deterministic proof" };

export default function ProofPage() {
  const suite = runProofSuite();
  const mutation = criticalMutationReceipt();
  return <section className="px-5 py-12 lg:px-10 lg:py-16"><div className="mx-auto max-w-[1360px]"><div className="flex flex-col justify-between gap-6 lg:flex-row lg:items-end"><div className="max-w-4xl"><p className="eyebrow">Deterministic proof</p><h1 className="display mt-4 text-5xl leading-[.95] sm:text-7xl">The detector is part of the claim.</h1><p className="mt-5 max-w-2xl text-base leading-7 text-[var(--muted)]">Every requirement carries a known-bad control, a clean control, a normalized receipt, an identical second-run digest, and a mutation check.</p></div><Badge tone="good">{suite.healthyCount}/{suite.totalCount} healthy</Badge></div>
    <div className="mt-12 grid gap-5 lg:grid-cols-[1fr_2fr]"><div className="space-y-5"><Card className="p-6"><Fingerprint className="text-[var(--signal)]" size={25} aria-hidden="true" /><p className="mt-8 text-xs font-bold uppercase tracking-[.16em] text-[var(--muted)]">Normalized suite digest</p><code className="mt-3 block break-all text-sm leading-6 text-[var(--signal-soft)]">{suite.suiteDigest}</code><p className="mt-5 text-xs leading-5 text-[var(--muted)]">The digest excludes wall-clock time. Two complete runs over the same versioned synthetic fixtures are byte-stable.</p></Card><Card className="p-6"><ShieldX className="text-[var(--danger-soft)]" size={25} aria-hidden="true" /><h2 className="mt-8 text-lg font-semibold">Critical mutation</h2><div className="mt-4 flex items-center justify-between border-t border-white/8 py-3 text-sm"><span>DET-CP-R4 disabled</span><Badge tone={mutation.mutationCaught ? "bad" : "unknown"}>{mutation.mutationCaught ? "Gate failed" : "Not caught"}</Badge></div><div className="flex items-center justify-between border-t border-white/8 py-3 text-sm"><span>Detector restored</span><Badge tone={mutation.restoredHealthy ? "good" : "bad"}>{mutation.restoredHealthy ? "Gate healthy" : "Still failing"}</Badge></div></Card></div>
    <Card className="overflow-hidden"><div className="grid grid-cols-[5rem_1fr_6rem] border-b border-white/8 px-5 py-4 text-[.68rem] font-bold uppercase tracking-[.14em] text-[var(--muted)] sm:grid-cols-[5rem_1fr_7rem_7rem]"><span>Rule</span><span>Control</span><span className="hidden sm:block">Repeat</span><span className="text-right">Health</span></div><div>{suite.controls.map((control) => <article key={control.requirementId} className="grid grid-cols-[5rem_1fr_6rem] items-center border-b border-white/6 px-5 py-4 last:border-0 sm:grid-cols-[5rem_1fr_7rem_7rem]"><span className="text-xs font-bold text-[var(--signal-soft)]">{control.requirementId}</span><div><h2 className="text-sm font-semibold">{control.label}</h2><p className="mt-1 hidden text-xs text-[var(--muted)] md:block">Bad: {control.badDecision.issueCode} · Clean: PASS</p></div><span className="hidden text-xs text-[var(--muted)] sm:block">{control.repeatable ? "Identical" : "Drifted"}</span><span className="justify-self-end"><Badge tone={control.status === "HEALTHY" ? "good" : "bad"}><Check size={11} aria-hidden="true" /> {control.status}</Badge></span></article>)}</div></Card></div>
    <p className="mt-5 text-xs leading-5 text-[var(--muted)]">Proof ceiling: these receipts prove the local deterministic implementation against committed synthetic fixtures. They do not prove customer demand, production operation, provider configuration, safety effectiveness, or commercial outcomes.</p></div></section>;
}
